### ISSUE TITLE
ANR in RemoteInterface and ServerRequest

### ISSUE THREAD

**Issue by rozag** [BranchMetrics/android-branch-deep-linking#238] opened 2016-05-05 12:42 UTC
Our users are experiencing ANRs (caught by [ANR-WatchDog](https://github.com/SalomonBrys/ANR-WatchDog)) in 2 cases:
**Case 1**:
_Stacktrace 1_:
> libcore.io.Posix.stat (Posix.java)
libcore.io.ForwardingOs.stat (ForwardingOs.java:130)
java.io.File.length (File.java:751)
org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.isTombstone (TrustedCertificateStore.java:176)
org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.findCert (TrustedCertificateStore.java:513)
org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.isTrustAnchor (TrustedCertificateStore.java:350)
org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.findTrustAnchorBySubjectAndPublicKey (TrustManagerImpl.java:525)
org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.cleanupCertChainAndFindTrustAnchors (TrustManagerImpl.java:369)
org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted (TrustManagerImpl.java:225)
org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted (TrustManagerImpl.java:202)
org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain (OpenSSLSocketImpl.java:595)
org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake (NativeCrypto.java)
org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake (OpenSSLSocketImpl.java:398)
libcore.net.http.HttpConnection.setupSecureSocket (HttpConnection.java:209)
libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection (HttpsURLConnectionImpl.java:478)
libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect (HttpsURLConnectionImpl.java:433)
libcore.net.http.HttpEngine.sendSocketRequest (HttpEngine.java:290)
libcore.net.http.HttpEngine.sendRequest (HttpEngine.java:240)
libcore.net.http.HttpURLConnectionImpl.connect (HttpURLConnectionImpl.java:81)
libcore.net.http.HttpURLConnectionImpl.getOutputStream (HttpURLConnectionImpl.java:197)
libcore.net.http.HttpsURLConnectionImpl.getOutputStream (HttpsURLConnectionImpl.java:281)
io.branch.referral.RemoteInterface.make_restful_post (RemoteInterface.java:333)
io.branch.referral.RemoteInterface.make_restful_post (RemoteInterface.java:261)
io.branch.referral.BranchRemoteInterface.make_restful_post (BranchRemoteInterface.java:7)
io.branch.referral.Branch$BranchPostTask.doInBackground (Branch.java:3214)
io.branch.referral.Branch$BranchPostTask.doInBackground (Branch.java:3191)
android.os.AsyncTask$2.call (AsyncTask.java:287)
java.util.concurrent.FutureTask.run (FutureTask.java:234)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:230)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1080)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:573)
java.lang.Thread.run (Thread.java:841)

_Stacktrace 2_:
> Fatal Exception: com.github.a.a: Application Not Responding
Caused by com.github.a.c: main
       at android.os.BinderProxy.transact(Binder.java)
       at android.app.ActivityManagerProxy.startService(ActivityManagerNative.java:2728)
       at android.app.ContextImpl.startServiceAsUser(ContextImpl.java:1399)
       at android.app.ContextImpl.startService(ContextImpl.java:1386)
       at android.content.ContextWrapper.startService(ContextWrapper.java:473)
       at com.google.android.gms.crash.internal.api.CrashApiImpl$1.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5121)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by com.github.a.c: Answers Events Handler1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1205)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:159)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2019)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1052)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:780)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1013)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1073)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
       at java.lang.Thread.run(Thread.java:841)
Caused by com.github.a.c: AsyncTask #1
       at libcore.io.Posix.stat(Posix.java)
       at libcore.io.ForwardingOs.stat(ForwardingOs.java:130)
       at java.io.File.length(File.java:751)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.isTombstone(TrustedCertificateStore.java:176)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.findCert(TrustedCertificateStore.java:513)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.findIssuer(TrustedCertificateStore.java:379)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.findTrustAnchorByIssuerAndSignature(TrustManagerImpl.java:501)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.cleanupCertChainAndFindTrustAnchors(TrustManagerImpl.java:384)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:225)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:202)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:595)
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(NativeCrypto.java)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:398)
       at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209)
       at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
       at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
       at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
       at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
       at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:282)
       at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
       at libcore.net.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:134)
       at com.facebook.GraphResponse.fromHttpConnection(GraphResponse.java:253)
       at com.facebook.GraphRequest.executeConnectionAndWait(GraphRequest.java:1266)
       at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:1164)
       at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:1130)
       at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:1114)
       at com.facebook.GraphRequest.executeAndWait(GraphRequest.java:1089)
       at com.facebook.GraphRequest.executeAndWait(GraphRequest.java:983)
       at com.facebook.internal.Utility.getAppSettingsQueryResponse(Utility.java:869)
       at com.facebook.internal.Utility.access$100(Utility.java:76)
       at com.facebook.internal.Utility$1.run(Utility.java:798)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
Caused by com.github.a.c: AsyncTask #2
       at libcore.io.Posix.stat(Posix.java)
       at libcore.io.ForwardingOs.stat(ForwardingOs.java:130)
       at java.io.File.length(File.java:751)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.isTombstone(TrustedCertificateStore.java:176)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.findCert(TrustedCertificateStore.java:513)
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateStore.isTrustAnchor(TrustedCertificateStore.java:350)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.findTrustAnchorBySubjectAndPublicKey(TrustManagerImpl.java:525)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.cleanupCertChainAndFindTrustAnchors(TrustManagerImpl.java:369)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:225)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:202)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:595)
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(NativeCrypto.java)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:398)
       at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:209)
       at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
       at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
       at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
       at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
       at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:81)
       at libcore.net.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
       at libcore.net.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:281)
       at io.branch.referral.RemoteInterface.make_restful_post(RemoteInterface.java:333)
       at io.branch.referral.RemoteInterface.make_restful_post(RemoteInterface.java:261)
       at io.branch.referral.BranchRemoteInterface.make_restful_post(BranchRemoteInterface.java:7)
       at io.branch.referral.Branch$BranchPostTask.doInBackground(Branch.java:3214)
       at io.branch.referral.Branch$BranchPostTask.doInBackground(Branch.java:3191)
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
Caused by com.github.a.c: AsyncTask #3
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1205)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:159)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2019)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:413)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1013)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1073)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
Caused by com.github.a.c: AsyncTask #4
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1205)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:159)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2019)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:413)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1013)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1073)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
Caused by com.github.a.c: AsyncTask #5
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1205)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:159)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2019)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:413)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1013)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1073)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)

**Case 2**:
_Stacktrace 1_:
> java.lang.VMThread.getStatus (VMThread.java)
java.lang.Thread.getState (Thread.java:599)
java.lang.Thread.getThreadGroup (Thread.java:614)
java.lang.Thread.create (Thread.java:400)
java.lang.Thread. (Thread.java)
io.branch.referral.ServerRequest.onRequestSucceeded (ServerRequest.java:341)
io.branch.referral.Branch$BranchPostTask.doInBackground (Branch.java:3262)
io.branch.referral.Branch$BranchPostTask.doInBackground (Branch.java:3245)
android.os.AsyncTask$2.call (AsyncTask.java:288)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:231)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:841)

_Stacktrace 2_:
> Fatal Exception: com.github.a.a: Application Not Responding
Caused by com.github.a.c: main
       at java.lang.BootClassLoader.findClass(ClassLoader.java:761)
       at java.lang.BootClassLoader.loadClass(ClassLoader.java:821)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:491)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
       at com.ourapp.main.MainActivity.onResume(MainActivity.java:568)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1198)
       at android.app.Activity.performResume(Activity.java:5530)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3066)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3105)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.access$900(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by com.github.a.c: Answers Events Handler1
       at com.android.org.conscrypt.NativeCrypto.X509_verify(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLX509Certificate.verifyOpenSSL(OpenSSLX509Certificate.java:334)
       at com.android.org.conscrypt.OpenSSLX509Certificate.verify(OpenSSLX509Certificate.java:367)
       at com.android.org.conscrypt.TrustedCertificateIndex.findByIssuerAndSignature(TrustedCertificateIndex.java:107)
       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:240)
       at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:202)
       at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:612)
       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
       at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
       at com.android.okhttp.Connection.connect(Connection.java:107)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
       at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:254)
       at io.fabric.sdk.android.services.network.HttpRequest.openOutput(HttpRequest.java:2449)
       at io.fabric.sdk.android.services.network.HttpRequest.startPart(HttpRequest.java:2462)
       at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2654)
       at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2616)
       at com.crashlytics.android.answers.SessionAnalyticsFilesSender.send(SessionAnalyticsFilesSender.java:45)
       at com.crashlytics.android.answers.AnswersRetryFilesSender.send(AnswersRetryFilesSender.java:49)
       at com.crashlytics.android.answers.EnabledSessionAnalyticsManagerStrategy.sendEvents(EnabledSessionAnalyticsManagerStrategy.java:154)
       at com.crashlytics.android.answers.AnswersEventsHandler$3.run(AnswersEventsHandler.java:103)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
       at java.lang.Thread.run(Thread.java:841)
Caused by com.github.a.c: AsyncTask #1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1205)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by com.github.a.c: AsyncTask #2
       at java.lang.VMThread.getStatus(VMThread.java)
       at java.lang.Thread.getState(Thread.java:599)
       at java.lang.Thread.getThreadGroup(Thread.java:614)
       at java.lang.Thread.create(Thread.java:400)
       at java.lang.Thread.(Thread.java)
       at io.branch.referral.ServerRequest.onRequestSucceeded(ServerRequest.java:341)
       at io.branch.referral.Branch$BranchPostTask.doInBackground(Branch.java:3262)
       at io.branch.referral.Branch$BranchPostTask.doInBackground(Branch.java:3245)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by com.github.a.c: AsyncTask #3
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1205)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by com.github.a.c: AsyncTask #4
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1205)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by com.github.a.c: AsyncTask #5
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1205)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

Thanks.

**Comment by sojanpr** [comment] 2016-05-05 16:33
@rozag Sorry that you are facing this issue. We are trying to reproduce and fix  it. Could you please provide the SDK version you are using? Also would really appreciate if you can help with any step to reproduce it

**Comment by rozag** [comment] 2016-05-05 18:55
We're using SDK 1.11.1 and unfortunately we don't know how to reproduce it.

**Comment by sojanpr** [comment] 2016-05-05 19:01
@rozag we are also unable to reproduce this. From the traces seems it could be caused  by a temporary SSL verification error on client side. Could you please help us with an ANR trace next time when this happens

**Comment by rozag** [comment] 2016-05-05 19:03
@sojanpr Sure. I'll notify you, when get more info about the issue. Thanks.

**Comment by sojanpr** [comment] 2016-05-05 19:12
@rozag Thank you much. We will also keep an eye on this

**Comment by sojanpr** [comment] 2016-05-26 23:49
@rozag  we checked on this for couple of releases and seems like we have no occurrence of this issue. It seems like an temperory  certificate error  happened may caused this. So closing this issue for now.  Thanks for your help

**Closed by sojanpr** 2016-05-26 23:49 UTC
