### ISSUE TITLE
Branch handling always the same link

### ISSUE THREAD

**Issue by ronaldo-getreveel** [BranchMetrics/android-branch-deep-linking#352] opened 2016-11-22 21:59 UTC
I am using Branch Android SDK 2.4.5 and everything was working fine until yesterday. 

In the Branch.initSession I'm getting always the same link info back. Its info from an old link generated last week. Its happening in all devices even if I restart or change network I'm connected to. 

This is happening only for Android. IOS is working fine. 

Ronaldo

**Comment by ronaldo-getreveel** [comment] 2016-11-23 17:54
Any idea guys?

**Comment by sojanpr** [comment] 2016-11-23 23:13
@ronaldo-getreveel it is surprising to see that you are getting the same result  even after restart.
Could you please write to our awesome support team integrations@branch.io to get a faster response

**Comment by aaustin** [comment] 2016-11-24 00:12
Ronaldo - since we don't believe this to be an SDK issue, and hopefully you've sent a ticket in to our integrations team, I'm going to close this out. I hope we get your problem resolved ASAP!

**Comment by ronaldo-getreveel** [comment] 2016-11-29 19:30
This issue is still happening and the reason is that when no link was clicked old link information are returning when the Branch Session is inited. 
Basically, the Branch.getInstance().getFirstReferringParams() are returned  when I init a session when no link was clicked. 

That is really annoying because every single time a user opens the app the first link is routed. 
And I compared all the parameters from the first link and when I  init a session without a link click and there is no property that I could idenfity to differ between a fresh link click. 

I sent a lot of info to the Integration Team and I'm not getting any feedback.
This is a huge problem to us, this is happening in production and we cannot solve without replacing Branch by another Deeplink solution. 

Kind regards.

**Comment by sojanpr** [comment] 2016-11-29 19:51
@ronaldo-getreveel Sorry that you are facing this issue.  `Branch.getInstance().getFirstReferringParams() ` always returns the  deeplink params associated with the link which first opened the app ever in your device. I think the method you are looking for is 
`Branch.getInstance().getLatestReferringParams()`.
 This method will get you the prams associated with latest session.

**Comment by ronaldo-getreveel** [comment] 2016-11-29 19:59
Before Nov 22nd the following routing function was working. Now its failing. 
The `referringParams` contained the last link clicked information, not it always contains a link:

- when the current session came from a link click (working great)
- when a normal app opening, the first link clicked

My question is, how to identify the link clicked once (and only once) and route it properly inside the routing function bellow?

````java
Branch branch = Branch.getInstance();
        branch.initSession(new Branch.BranchReferralInitListener() {
            @Override
            public void onInitFinished(JSONObject referringParams, BranchError error) {
                boolean handled = false;
                if (error == null) {
                    // accepting an invite
                        if (referringParams.has("invite_token")) {
                            if (referringParams.has("+clicked_branch_link") && referringParams.optBoolean("+clicked_branch_link")) {
                                saveDeeplinkReferrer(new DeepLink(token, type, id));
                            }
                    }
                }else{
                    presenter.checkUserState();
                }
            }
        }, this.getIntent().getData(), this);
````

Thanks.

**Comment by sojanpr** [comment] 2016-11-29 20:07
@ronaldo-getreveel  In the above example seems correct to me. Are you facing the issue that the params you receive  are  from a  previous link click? If so can you please check that  you are overriding `onNewIntent` in your main activity.
```
@Override
    public void onNewIntent(Intent intent) {
        this.setIntent(intent);
    }
```

**Comment by ronaldo-getreveel** [comment] 2016-11-29 20:10
Yes, the params I'm getting are from the first link the user clicked (when the session starts fresh, not by a link click). 

My onNewIntent is properly setted: 
````java
@Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        super.setIntent(intent);
        setIntent(intent);
    }
````
The routing function is inside `onStart()` and my activity launchMode is setted to `singleTask`.

**Comment by ronaldo-getreveel** [comment] 2016-11-29 20:14
Yes @sojanpr, you are right. I'm facing that issue. 
I sent a lot of info by the integration team but no answer this week.

**Comment by sojanpr** [comment] 2016-11-29 22:07
@ronaldo-getreveel could you please confirm that you are using the latest version of Branch SDK. We have  seen some issues with intent not getting updated and added a fi on v2.0.2

**Comment by ronaldo-getreveel** [comment] 2016-11-29 22:54
@sojanpr  I'm using the SDK 2.5.1.

**Comment by ronaldo-getreveel** [comment] 2016-11-30 16:30
Summing up all the issue mapping I made: 

### Android SDK 7.0+

1. App opens fresh (no link click)
	* newIntent() is never called
	* getIntent().getData() is null (no link info here)
	* referringParams contains old link (always the same link)

2. App opens from a link click
	* newIntent() never called
	* getIntent() with the right link data
	* referringParams contains old link (always the same link


### Android SDK 7.0- (tested from 4.4 to 6.0)

1. App opens fresh (no link click)
	* getIntent().getData() is null 
	* referringParams contains old link (always the same link)
	* newIntent() never called

2. App opens from a link click
	* referringParams with the right link (working fine)
	* getIntent().getData() with the right data
	* newIntent() never called

**Comment by spiritinlife** [comment] 2016-12-03 15:41
I think i have the same issues with @ronaldo-getreveel using the latest sdk 2.5.2

I believe the problem has something to do with fb app invite links, because if i never click on a fb app invite link and click on other links shared by my app everything works fine, meaning i always get the correct clicked link content.
Now if at some point i click a facebook app link my app opens correctly with the fb app link content which is correct. But after that if i close and open the app or if i open it clicking any other link i always get the same fb app link content that was clicked before and nothing else.

Any ideas?

**Comment by aaustin** [comment] 2016-12-04 00:49
Ronaldo and I are working on this in another thread. It appears to be a bug with the Facebook SDK that's returning this deep link data to us repeatedly. Something must have changed in their recent SDK. We're still investigating on our side. More soon!

**Comment by aaustin** [comment] 2016-12-04 01:10
I just found that we had defaulted our Facebook SDK check to true, where it should be set to false. This means that all integrations are susceptible to this Facebook bug. This PR (https://github.com/BranchMetrics/android-branch-deep-linking/pull/356) will disable it and we'll try to get this deployed asap.

**Comment by spiritinlife** [comment] 2016-12-04 15:16
@aaustin I made a test with your solution rom the PR you mentioned but it does not seem to work again. It worked for some links but for other it still returns the clicked app invite.

**Comment by aaustin** [comment] 2016-12-04 18:14
Hey @spiritinlife - Thanks for the comment. Can you stop calling `enableFacebookAppLinkCheck` as described here? https://dev.branch.io/features/facebook-ads/guide/android/#option-2-connect-branch-to-the-facebook-sdk

Please use our server side integration which will correctly clear the App Link after it is retrieved.

**Comment by spiritinlife** [comment] 2016-12-04 20:29
@aaustin i am not calling this method at all.
I have used the option 1 as explained in the facebook app invites guide
https://dev.branch.io/features/facebook-app-invites/guide/android/ which i was interested in.

**Comment by aaustin** [comment] 2016-12-05 17:51
Hey @spiritinlife - I'm trying to reproduce today. I'll let you know what I find.

**Comment by aaustin** [comment] 2016-12-06 06:15
@spiritinlife Dang - I'm having a hard time reproducing. Can you see if this is being called from your test with that boolean corrected? https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/DeferredAppLinkDataHandler.java#L40

**Comment by spiritinlife** [comment] 2016-12-07 13:11
@aaustin sorry for the delay i will check it out today.

**Comment by spiritinlife** [comment] 2016-12-07 17:35
@aaustin i cannot reproduce it either today. I haven't changed anything though so i don't know why i cannot.
From my viewpoint this is resolved with the #356 .

Thank you for the support!

**Comment by aaustin** [comment] 2016-12-07 17:36
Great news!

**Closed by aaustin** 2016-12-07 17:36 UTC

**Comment by raheeladnan** [comment] 2016-12-14 15:41
I am facing the same issue, we are not using it with Facebook SDK. onInitFinished(JSONObject referringParams, BranchError error) the referingParams always give us wrong ~referring_link
