### ISSUE TITLE
RuntimeException in Branch.java line 1211

### ISSUE THREAD

**Issue by okaybroda** [BranchMetrics/android-branch-deep-linking#239] opened 2016-05-12 09:05 UTC
Possibly a missing try catch? Below is the stack trace from Crashlytics.

`Caused by java.lang.RuntimeException: Parcel android.os.Parcel@1db9c98b: Unmarshalling unknown type code 3473457 at offset 856
       at android.os.Parcel.readValue(Parcel.java:2228)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
       at android.os.BaseBundle.unparcel(BaseBundle.java:221)
       at android.os.BaseBundle.getString(BaseBundle.java:918)
       at io.branch.referral.Branch.readAndStripParam(Branch.java:1211)
       at io.branch.referral.Branch.initSessionWithData(Branch.java:861)
       at io.branch.referral.Branch$BranchActivityLifeCycleObserver.onActivityStarted(Branch.java:3043)
       at android.app.Application.dispatchActivityStarted(Application.java:223)
       at android.app.Activity.onStart(Activity.java:1357)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1264)
       at android.app.Activity.performStart(Activity.java:6647)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3096)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3243)
       at android.app.ActivityThread.access$1000(ActivityThread.java:218)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1718)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6917)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)`

**Comment by sojanpr** [comment] 2016-05-12 16:56
@okaybroda Sorry to see that you have the following issue. We will add a try-catch to prevent this asap. 

Mean while could you please help to find the real issue. Is there any chance that you are adding  a value with key `branch` to your intent?

**Comment by okaybroda** [comment] 2016-05-13 02:21
@sojanpr hi, thank you for the quick fix!

I can't reproduce this though. Must be an edge edge case.

**Comment by sojanpr** [comment] 2016-05-13 16:27
@okaybroda Thanks for testing

**Comment by sojanpr** [comment] 2016-05-26 23:42
@okaybroda  Since we added the safety try-catch and were not able to reproduce it closing this issue  for now. Thanks for your helps

**Closed by sojanpr** 2016-05-26 23:42 UTC
