### ISSUE TITLE
Memory leak on BranchReferralInitListener

### ISSUE THREAD

**Issue by sirajsolutelabs** [BranchMetrics/android-branch-deep-linking#380] opened 2017-01-17 05:29 UTC
I have the splash screen in which I am initialising branch.io as follows:

`Branch branch = Branch.getInstance();

        branch.initSession(new Branch.BranchReferralInitListener() {
            @Override
            public void onInitFinished(JSONObject referringParams, BranchError error) {
                try {
                   // My Code
                } catch (Exception e) {
                    e.printStackTrace();
                }
                if (error == null) {
                    // params are the deep linked params associated with the link that the user clicked -> was re-directed to this app
                    // params will be empty if no data found
                    // ... insert custom logic here ...
                } else {
                    Timber.d("MyApp" + error.getMessage());
                }
            }
        }, this.getIntent().getData(), this);`

Getting the memory leak from leak canary as shown in below screenshot:

![img_20170117_105823](https://cloud.githubusercontent.com/assets/19490880/22008760/031350c6-dca4-11e6-9471-c6597cbe70a7.jpg)

Please help how to fix this leak.

**Comment by EvangelosG** [comment] 2017-01-17 18:11
Hi @sirajsolutelabs -- we're looking into this now, thanks for reporting!

**Comment by EvangelosG** [comment] 2017-01-17 18:19
Hi @sirajsolutelabs -- where are you making the init call? When I drop your code into onStart w/ LeakCanary running, I'm not able to generate any canary notifications. When/where are you calling getAutoInstance? Can you share all your Branch related code, referencing where each snippet is being used? Steps to reproduce this leak would be helpful as well! Thanks.

**Comment by sirajsolutelabs** [comment] 2017-01-18 05:18
Hi @EvangelosG, Thanks for the quick response. As shown in above question, The initSession code is in onStart() method of my SplashActivity - The main launcher activity. 

The getAutoInstance method is in Application class as given below:

`public class AppApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        // initialize the Branch object for invite functionality
        Branch.getAutoInstance(this);

       // Other codes
     }
}`

Now I am using Branch io for invite in InviteActivity. The leak is in SplashActivity

**Comment by EvangelosG** [comment] 2017-01-18 21:51
Thanks for the additional information. How are you handling Branch in your Splash Activity? Can you show me your code for traversing to the next activity? I'm still struggling to reproduce the leak. If you want to use our sample app to show me how to reproduce the leak, that would be incredibly helpful! It lives here and already has LeakCanary, just un-comment in the Application class and add the needed dependency: https://github.com/BranchMetrics/android-branch-deep-linking/tree/master/Branch-SDK-TestBed

**Comment by sojanpr** [comment] 2017-05-26 17:24
Closing this for now since our test not able to reproduce the leak

**Closed by sojanpr** 2017-05-26 17:24 UTC

**Comment by bkraszewski** [comment] 2017-09-14 07:37
@sirajsolutelabs I had similar issue, noticed memory leak during opening splash screen.
![image](https://user-images.githubusercontent.com/773849/30417419-fa98b708-992f-11e7-8fb5-f9d8db438c4f.png)

It's hard to reproduce, but actual result might be anonymous implementation of BranchReferralInitListener. I replaced it with static class that uses weak reference to activity and so far problem is solved:

    private static class OnBranchInitializedHandler implements Branch.BranchReferralInitListener {
        private final WeakReference<Activity> ref;

        public OnBranchInitializedHandler(Activity activity){
           ref = new WeakReference<>(activity);
	}
    }

**Comment by sojanpr** [comment] 2017-09-14 18:48
@bkraszewski  Thanks of the above test and details. Certainly it is leaking a reference set to the callback but what would be the reason of launching a new activity while you are waiting on an activity  to get the results Branch Initialization?
 Is there a  use case for you to launch a new activity while waiting for the Branch  Init Session callback? If so can you try to move the callback from Activity to some other place (Say application class) since Android will try to kill no more used Activities

If you still want to keep the Branch callback in the Activity, can you please  try calling `startActivityForResult()`  when launching the new activity.

**Comment by bkraszewski** [comment] 2017-09-14 20:00
@sojanpr No chance to launch other activity, but I think case might be:

- user launches app, splash screen appears
- user navigates back finishing activity before branch is initialized
- activity is cleaned up due to heavy memory usage for phone
- memory leak

**Comment by sojanpr** [comment] 2017-09-14 20:15
@bkraszewski  Good point. I think that should be the only case. We will fix the code  to hold only weak reference to `Branch.BranchReferralInitListener` . Will update here when we release it
