### ISSUE TITLE
A resource was acquired at attached stack trace but never released. 

### ISSUE THREAD

**Issue by SumeraMartin** [BranchMetrics/android-branch-deep-linking#648] opened 2018-11-13 14:48 UTC
```
11-13 09:31:56.027 2001-2011/com.google.android.gms E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:184)
        at com.google.android.gms.org.conscrypt.Platform.closeGuardOpen(:com.google.android.gms:383)
        at com.google.android.gms.org.conscrypt.OpenSSLSocketImpl.startHandshake(:com.google.android.gms:297)
        at com.google.android.gms.org.conscrypt.PreKitKatPlatformOpenSSLSocketImplAdapter.startHandshake(:com.google.android.gms:318)
        at com.google.android.gms.common.net.SSLCertificateSocketFactory.verifyHostname(:com.google.android.gms:217)
        at com.google.android.gms.common.net.SSLCertificateSocketFactory.createSocket(:com.google.android.gms:507)
        at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:197)
        at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
        at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
        at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
        at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
        at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:81)
        at libcore.net.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
        at libcore.net.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:281)
        at fla.a(:com.google.android.gms:386)
        at fla.a(:com.google.android.gms:249)
        at fks.a(:com.google.android.gms:825)
        at fks.doInBackground(:com.google.android.gms:792)
        at android.os.AsyncTask$2.call(AsyncTask.java:287)
        at java.util.concurrent.FutureTask.run(FutureTask.java:234)
        at java.lang.Thread.run(Thread.java:841)
```

I'm getting this error on Samsung S3 mini with API version 4.4.2 since I have updated from version 2.14.1 to 3.0.0. I did not change the code at all.

**Comment by SumeraMartin** [comment] 2019-01-05 10:58
I'm sorry but I don't have access to the codebase anymore.

**Comment by csalmi-branch** [comment] 2019-01-25 23:15
I am closing this issue due to not enough information to reproduce. If anyone else if having a similar problem, please open up a ticket with our support team (support.branch.io) or open a new github issue.

**Closed by csalmi-branch** 2019-01-25 23:15 UTC
