### ISSUE TITLE
Problem if minimizing app before onInitFinished callback

### ISSUE THREAD

**Issue by edinaleitner** [BranchMetrics/android-branch-deep-linking#319] opened 2016-10-22 12:06 UTC
Hello,
we found the following problem on Android:
1. Click a branch link (Branch.getAutoTestInstance is called, Branch.getTestInstance().initSession(...) is called)
2. Minimize the app right after the click (in such way that onInitFinished callback is not received yet)
3. Wait to receive the onInitFinished callback (while app minimized)
4. Click the branch link again

Issue: onInitFinished is received with referringParams == {}

*easier to reproduce with slow internet connection
*attached commented logs

[logs_minimize-issue.txt](https://github.com/BranchMetrics/android-branch-deep-linking/files/545757/logs_minimize-issue.txt)

**Comment by sojanpr** [comment] 2016-10-23 02:28
@edinaleitner Sorry that you are facing the issue. Can you please make sure you are doing the following things correctly in your app
1) `Branch.getAutoTestInstance(Application application)` is called from `onCreate()` method of your `Application` class

2) Use `Branch.getInstance()` (Not `Branch.getAutoTestInstance`) when you want to access  Branch instance. For e.g..
 ```public MyActivity extends Activity {
  .......
  public void onStart() {
      super.onStart();
      Branch.getInstance().initSession(...);
  }
 ......
}```

**Comment by edinaleitner** [comment] 2016-10-24 08:52
@sojanpr , thank you for your response:

1) i am calling Branch.getAutoTestInstance(Application application) in the onCreate of Application class
2) i am using Branch.getTestInstance() in the onResume method (not in onStart) like this:

public MyActivity extends Activity {
  .......
  public void onResume() {
      super.onResume();
      Branch.getTestInstance(this).initSession(...);
  }
 ......
}

**Comment by sojanpr** [comment] 2016-10-24 17:06
@edinaleitner  Thanks for your response can you please replace the code `onResume()` to `Branch.getInstance().initSession()` as suggested in the above example.  You can get Branch instance from any where  using `Branch.getInstance()` method  other than application  `Appplication.onCreate()`
Could you please give it a try and update?

**Comment by edinaleitner** [comment] 2016-10-25 13:50
@sojanpr , i'm not sure what you mean. 
I am using the initSession code exactly as in your example, the only difference is that i call Branch.getTestInstance(Activity) not Branch.getInstance() - since we are in the testing phase only.

**Comment by sojanpr** [comment] 2016-10-25 16:59
@edinaleitner 
Here is the code snippet
```
public final class MyApp extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        Branch.getAutoTestInstance(this); // Create a debug instance of branch
    }
}```

Now you can get the created instance of Branch in your activity using `getInstance()` method. It will return  the test instance  since  the instance created in application class is a test instance.
```
public MyActivity extends Activity {
  .......
  public void onStart() {
      super.onStart();
      Branch.getInstance().initSession(...); // Branch.getInstance() will return the already created test/live instance of branch
  }
 ......
}
```

**Comment by sojanpr** [comment] 2016-10-25 18:24
@edinaleitner  Thank you very much for the logs . The issue is  reproducible and a fix is being worked on now. Really sorry for the  delay, Will update as soon as we  have a PR for this issue

**Comment by sojanpr** [comment] 2016-10-25 21:12
@edinaleitner  Thank you very much for this report. We have opened a PR for this issue https://github.com/BranchMetrics/android-branch-deep-linking/pull/322
Will be released after QA pass

**Comment by edinaleitner** [comment] 2016-10-26 08:18
@sojanpr thank you! no problem with the delay. looking forward for the fix.

**Comment by sojanpr** [comment] 2016-11-01 00:49
@edinaleitner  We have released v2.4.7 with the fix. Could you please give it a try and update here

**Comment by pikaboo** [comment] 2016-11-01 13:12
Your newest version CAUSED  this issue for us. Please review your fix.

**Comment by pikaboo** [comment] 2016-11-01 13:15
Version 2.4.7 CAUSED this issue for us, yesterday there was no such problem. Please review your fix asap!

**Comment by edinaleitner** [comment] 2016-11-01 14:41
@sojanpr , v2.4.7 fixed the issue for us. thank you.

**Comment by sojanpr** [comment] 2016-11-01 16:54
@pikaboo  Sorry that you are facing this issue. Could you please help us by providing  a little bit more description on the issue and the logs if possible? Are you calling `initSession` from `onStart()` of your activity.

**Comment by sojanpr** [comment] 2016-11-02 17:09
@pikaboo  Did the above helped or do you still have the issue. We couldn't reproduce this with our test apps. If you still face this issue could you please help with logs and steps to reproduce

**Comment by sojanpr** [comment] 2016-11-07 23:51
@pikaboo  Were you able to get it working with  the above suggestion. Would you like to close this issue in this case?

**Comment by sojanpr** [comment] 2016-11-10 17:48
@pikaboo closing it for now since we could not  reproduce it. Please re-open if you face the issue again

**Closed by sojanpr** 2016-11-10 17:48 UTC

**Comment by sojanpr** [comment] 2016-11-16 21:41
@pikaboo We saw some partners got this issue with latest version when they call init session from `onCreate()` method of Activity . Our suggested way is to call initSession() in onStart() method of activity. Could you please make sure you are calling initSession() from onStart() method
