### ISSUE TITLE
Branch initialization stuck with INSTALL_REFERRER_FETCH_WAIT_LOCK

### ISSUE THREAD

**Issue by mikhailmelnik** [BranchMetrics/android-branch-deep-linking#547] opened 2018-02-15 18:48 UTC
It might be related only to the particular integration I'm doing but the call sequence looks legit so it feels like an issue.

Basically I found that Branch SDK calls stuck when app is installed from Play Store or using `adb install` with following `adb shell am broadcast -a com.android.vending.INSTALL_REFERRER -n <package_name>/io.branch.referral.InstallListener --es referrer "test_referrer=test"` command.

The locking sequence is following:

```
request.addProcessWaitLock(ServerRequest.PROCESS_WAIT_LOCK.INSTALL_REFERRER_FETCH_WAIT_LOCK); at Branch.java:2316
InstallListener.captureInstallReferrer(playStoreReferrerFetchTime, this); at Branch.java:2317
reportInstallReferrer(); at InstallListener.java:40
callback_.onInstallReferrerEventsFinished(); at InstallListener.java:114
requestQueue_.unlockProcessWait(ServerRequest.PROCESS_WAIT_LOCK.INSTALL_REFERRER_FETCH_WAIT_LOCK); at Branch.java:1530
for (ServerRequest req : queue) at ServerRequestQueue.java:372
```

i.e. in the first line code sets lock on current request and tries to remove it (synchronously in my case) in the last line, but, unfortunately the call itself is not in the queue yet so stays locked forever.

**Comment by sojanpr** [comment] 2018-02-15 19:07
@mikhailmelnik We have seen a corner case causing this particular issue  when there is no internet connection at the time of install. We have fixed this issue in v2.14.5. Can you please make sure you are using v2.14.5 or above

**Comment by mikhailmelnik** [comment] 2018-02-15 19:17
@sojanpr here is exact line from my gradle file `implementation('io.branch.sdk.android:library:2.14.5') { exclude module: 'answers-shim' }` and during debugging session (as well as when I was installing app from Play Store) device was always online.

**Comment by sojanpr** [comment] 2018-02-15 20:02
@mikhailmelnik Thanks for the update . Is this happening on a second init using se `force_branch session` call? Can you please  provide the steps if you do initilaise Branch in a custom way

**Comment by mikhailmelnik** [comment] 2018-02-15 20:20
@sojanpr I can't check it right now but from what I remember it happens only on the first app launch. 

I'm using Branch SDK the following way:

Application.onCreate: 
```
        Branch.enableLogging();
        // Branch.setPlayStoreReferrerCheckTimeout(0);  <-- this is workaround
        Branch.getAutoInstance(application);
```
and then in the custom callback (which occurs when required part of the app is ready, so a few activities might be shown during this time, or none when app launch is initiated by `adb shell ...` command):
```
Branch.getInstance().setIdentity(CUSTOM_IDENTITY, (referringParams, error) -> {
    // code which is never called under mentioned conditions
}
```

**Comment by sojanpr** [comment] 2018-02-15 22:11
@mikhailmelnik  I could reproduce this issue with some other steps. Working on a fix and update you soon. Thanks for brining it to attention

**Comment by sojanpr** [comment] 2018-02-15 22:50
@mikhailmelnik Opened a new PR for fixing this issue. https://github.com/BranchMetrics/android-branch-deep-linking/pull/548. Really appreciate if you can review it.

**Comment by sojanpr** [comment] 2018-02-16 00:07
@mikhailmelnik Fix is released with v2.15.1. Can you please try this version

**Closed by sojanpr** 2018-02-16 00:07 UTC

**Comment by mikhailmelnik** [comment] 2018-02-17 06:46
@sojanpr sorry for delay with reply, was offline whole day. I had checked PR (don't know internals but change looks reasonable) and tested the new version. Can't say for sure how it will behave in production but it works well in my synthetic test. 

I've noticed one more thing in the logcat after upgrade, even after `Invalidate caches/restart`, not sure about the reason and how critical it is:
```
I/art: Rejecting re-init on previously-failed class java.lang.Class<io.branch.referral.InstallListener$ReferrerClientWrapper$1>
I/art: Rejecting re-init on previously-failed class java.lang.Class<io.branch.referral.InstallListener$ReferrerClientWrapper$1>
```

**Comment by sojanpr** [comment] 2018-02-18 02:08
@mikhailmelnik Thanks for testing and updating.
The log in the above comment is caused by an optional dependency. It is only a warning depend ending on your config. Here is more notes on it. https://github.com/BranchMetrics/android-branch-deep-linking#proguard-warning-or-errors-with-appindexing-module.
Thanks

**Comment by mikhailmelnik** [comment] 2018-02-19 10:20
@sojanpr the link you've mentioned is about Proguard warning while I see these log entries in logcat on the app's startup. 

If I understand it correctly the runtime engine can't load `io.branch.referral.InstallListener$ReferrerClientWrapper$1` class but there is no such class at all. I've compared the source code with the decompiled one from the release build with disabled Proguard and can't find any difference or trace of what might be an inner class in this case.

**Comment by sojanpr** [comment] 2018-02-19 17:26
@mikhailmelnik Thanks for the details. We are looking into it.
Could you please check if your app  has a dependency on 'com.android.installreferrer:installreferrer:1.0' or above. We use this as an optional dependency for getting install referrer 
https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/InstallListener.java#L92

**Comment by mikhailmelnik** [comment] 2018-02-19 17:29
@sojanpr no, there is no such dependency in the project. Should it be added? Could you please point me to the related article if any?

**Comment by sojanpr** [comment] 2018-02-19 17:39
@mikhailmelnik it is an optional dependency. No need  to add it. Wondering if any other dependency your app has already adding it.

**Comment by mikhailmelnik** [comment] 2018-02-19 18:32
@sojanpr just checked the output of `.\gradlew.bat app:dependencies` and there is no such dependency in the whole project.

**Comment by sojanpr** [comment] 2018-02-19 18:33
@mikhailmelnik  thanks for checking it. Trying to reproduce the issue and get back to you soon

**Comment by sojanpr** [comment] 2018-02-19 19:07
@mikhailmelnik
Since it looks  like Dalvik is trying to load a non-added dependency, could you please help with the following
1) Disable Instant run and try again (Doesn't make much sense to me either but there was an bug causing this in IR)
2) Add pro-guard since proguard will strip of the non included dependencies from JAR.

If none of the above work can you please update and try this work around until we  have the real issue fixed
1) add dependency `'com.android.installreferrer:installreferrer:1.0' `

**Comment by mikhailmelnik** [comment] 2018-02-19 20:09
@sojanpr the strange thing is I've tried both enabled and disabled proguard and it didn't make any difference. Also all of the experiments were taken on the result of `.\gradlew.bat installRelease` after full cleanup and cache invalidation so I'm pretty sure it is not the Instant Run issue.

Suggested workaround with optional dependency removed these messages but what does it actually do?

**Comment by sojanpr** [comment] 2018-02-19 20:44
@mikhailmelnik Thanks for trying it. The optional  dependency is to support more accurate install attribution using google play install referrer  library
