### ISSUE TITLE
Sharing a deeplink on Pinterest the Google Play app is opened instead of Pinterest

### ISSUE THREAD

**Issue by joaquindrop** [BranchMetrics/android-branch-deep-linking#599] opened 2018-08-16 10:30 UTC
It seems there's a bug related to sharing deeplinks on Pinterest:

- Given the same configuration that you have posted on the documentation for sharing a deep link using the SDK version 2.16.0 at first attempt and the 2.19.2 in the second instance.
- When I try to share a deep link through Pinterest
- Then instead of opening the Pinterest app, the Google Play Store app is opened pointing to our app.

That happens just with Pinterest, trying the same flow using any other channel (Whatsapp, Facebook, Gmail, Twitter, Instagram...) the behaviour is perfect.

I currently checked as well to share something on Pinterest without using Branch and the result is the expected one.

**Comment by aaaronlopez** [comment] 2018-08-22 17:42
Hi @joaquindrop, we are able to reproduce this issue. We are working on a fix.

**Comment by Sarkar** [comment] 2018-10-19 16:33
@joaquindrop, it looks like this isn't reproducible anymore. We'll close this out, let us know if you have further issues.

**Closed by Sarkar** 2018-10-19 16:33 UTC

**Comment by joaquindrop** [comment] 2018-10-23 14:44
I tried right now with the latest version `2.19.5` and the issue is still easy to reproduce.

**Comment by aaaronlopez** [comment] 2018-10-26 02:48
@joaquindrop it could be a specific version of Pinterest on specific models that are causing the issues. Have you been able to reproduce with Android's default share feature by any chance? If you could be share:

1. Video of Branch share sheet issue
2. Video of Behavior with Android's default share feature
3. OS Model and Version # 
4. Pinterest app version number
