### ISSUE TITLE
Default timeout of 3 seconds not respected

### ISSUE THREAD

**Issue by edinaleitner** [BranchMetrics/android-branch-deep-linking#556] opened 2018-03-08 08:15 UTC
Hello!
We have on scenario when branch.initSession responds after 3 minutes - if low internet connection.
The default timeout of 3 seconds, as stated in the javadocs is not respected.
Is this normal, or is it a bug?
used v.2.14.5, but can be reproduced in v.2.16.0 also.

**Comment by sojanpr** [comment] 2018-03-08 20:08
@edinaleitner We know about this issue and it is caused by `URLConnection` class bug in Java. If you check the URLConnection time out implementation, the time out is repeated per each DNS resolved IP addresses.
Branch is using `URLConnection` by default for networking. We will be fixing this is issue soon.

Branch SDK is added an option to implement your own network implementation in case you want to have more control or you want to use  any other libraries like `Volley` `OKHttp` etc.
Here is how you add a custom network interface
https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/Branch.java#L449
Here is the abstract interface
https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/network/BranchRemoteInterface.java

**Comment by sojanpr** [comment] 2018-03-16 16:27
@edinaleitner  Does the above help. Do you think we can close this issue now?

**Closed by sojanpr** 2018-03-16 16:27 UTC
